import type { PlanDayKey, PlanItem } from "./types";

export function seedSydneyPlan(): Record<
  PlanDayKey,
  Omit<PlanItem, "id" | "createdAt" | "updatedAt" | "createdBy">[]
> {
  return {
    mon: [],
    tue: [],
    wed: [
      {
        day: "wed",
        startTime: "18:30",
        endTime: "20:00",
        title: "Dinner (near home / relaxed)",
        note: "Welcome dinner + easy night",
      },
      {
        day: "wed",
        startTime: "20:00",
        title: "Rest & sleep",
        note: "Early night (big days coming)",
      },
    ],
    thu: [
      { day: "thu", startTime: "08:30", title: "Leave home" },
      {
        day: "thu",
        startTime: "09:00",
        endTime: "09:30",
        title: "Arrive at Circular Quay",
        note: "Coffee / photos / tickets",
        mapUrl: "https://maps.google.com/?q=Circular+Quay+Sydney",
      },
      {
        day: "thu",
        startTime: "09:45",
        endTime: "10:15",
        title: "Ferry: Circular Quay → Manly",
        note: "🚢",
        mapUrl: "https://maps.google.com/?q=Manly+Wharf",
      },
      {
        day: "thu",
        startTime: "10:15",
        endTime: "12:30",
        title: "Manly Beach walk + The Corso",
        note: "Relax, photos",
        mapUrl: "https://maps.google.com/?q=Manly+Beach",
      },
      {
        day: "thu",
        startTime: "12:30",
        endTime: "13:30",
        title: "Lunch at Manly",
        mapUrl: "https://maps.google.com/?q=Restaurants+near+Manly+Beach",
      },
      {
        day: "thu",
        startTime: "14:00",
        endTime: "14:30",
        title: "Ferry: Manly → Circular Quay (return)",
        mapUrl: "https://maps.google.com/?q=Circular+Quay+Wharf",
      },
      {
        day: "thu",
        startTime: "14:45",
        endTime: "15:30",
        title: "Opera House walk + Harbour Bridge views",
        mapUrl: "https://maps.google.com/?q=Sydney+Opera+House",
      },
      {
        day: "thu",
        startTime: "15:30",
        endTime: "16:15",
        title: "Walk / light travel to Darling Harbour",
        mapUrl: "https://maps.google.com/?q=Darling+Harbour",
      },
      {
        day: "thu",
        startTime: "16:15",
        endTime: "17:45",
        title: "Darling Harbour walk",
        note: "Optional: Sea Life Aquarium OR Madame Tussauds (choose one)",
        mapUrl: "https://maps.google.com/?q=Darling+Harbour",
      },
      {
        day: "thu",
        startTime: "18:00",
        endTime: "19:00",
        title: "Momo’s Hub – Dinner 🥟",
        mapUrl: "https://maps.google.com/?q=Momo%27s+Hub+Sydney",
      },
      {
        day: "thu",
        startTime: "19:00",
        endTime: "20:00",
        title: "Travel back home",
      },
    ],
    fri: [
      {
        day: "fri",
        startTime: "08:00",
        endTime: "11:30",
        title: "Morning rest + pack bags + light breakfast",
      },
      {
        day: "fri",
        startTime: "12:00",
        title: "Leave Sydney → Blue Mountains",
        note: "🚗 / 🚆",
        mapUrl: "https://maps.google.com/?q=Katoomba+NSW",
      },
      {
        day: "fri",
        startTime: "14:00",
        endTime: "14:30",
        title: "Arrive & check-in (or drop bags)",
      },
      {
        day: "fri",
        startTime: "15:00",
        endTime: "17:00",
        title: "Free time",
        note: "Short walks / views / rest",
      },
      {
        day: "fri",
        startTime: "18:00",
        endTime: "22:00",
        title: "BBQ night 🔥 + Rakshi night 🍶",
      },
      {
        day: "fri",
        startTime: "22:00",
        title: "Sleep at Blue Mountains hotel",
      },
    ],
    sat: [
      {
        day: "sat",
        startTime: "08:00",
        endTime: "09:00",
        title: "Breakfast + get ready",
      },
      {
        day: "sat",
        startTime: "09:30",
        endTime: "10:30",
        title: "Echo Point / Three Sisters",
        mapUrl: "https://maps.google.com/?q=Echo+Point+Lookout",
      },
      {
        day: "sat",
        startTime: "11:00",
        endTime: "13:30",
        title: "Scenic World",
        note: "Cableway • Skyway • Railway",
        mapUrl: "https://maps.google.com/?q=Scenic+World+Katoomba",
      },
      {
        day: "sat",
        startTime: "13:30",
        endTime: "14:30",
        title: "Lunch (Leura / Katoomba)",
        mapUrl: "https://maps.google.com/?q=Restaurants+Leura+NSW",
      },
      {
        day: "sat",
        startTime: "15:00",
        endTime: "16:00",
        title: "Leura Village (shops + café)",
        mapUrl: "https://maps.google.com/?q=Leura+Mall",
      },
      {
        day: "sat",
        startTime: "16:30",
        endTime: "17:30",
        title: "Wentworth Falls (short walk only)",
        mapUrl: "https://maps.google.com/?q=Wentworth+Falls",
      },
      {
        day: "sat",
        startTime: "18:30",
        title: "Dinner + relax",
        note: "Night rest in Blue Mountains",
      },
    ],
    sun: [
      { day: "sun", startTime: "07:30", title: "Breakfast & checkout" },
      {
        day: "sun",
        startTime: "08:00",
        title: "Leave Blue Mountains → Helensburgh",
        note: "🚗",
        mapUrl: "https://maps.google.com/?q=Helensburgh+NSW",
      },
      {
        day: "sun",
        startTime: "11:00",
        endTime: "11:30",
        title: "Sea Cliff Bridge (photos + short walk)",
        mapUrl: "https://maps.google.com/?q=Sea+Cliff+Bridge",
      },
      {
        day: "sun",
        startTime: "12:30",
        endTime: "13:30",
        title: "Lunch (Kiama area)",
        mapUrl: "https://maps.google.com/?q=Restaurants+Kiama",
      },
      {
        day: "sun",
        startTime: "13:30",
        endTime: "14:00",
        title: "Kiama Blowhole",
        mapUrl: "https://maps.google.com/?q=Kiama+Blowhole",
      },
      {
        day: "sun",
        startTime: "15:30",
        endTime: "16:30",
        title: "Nan Tien Temple",
        mapUrl: "https://maps.google.com/?q=Nan+Tien+Temple",
      },
      {
        day: "sun",
        startTime: "16:30",
        endTime: "18:30",
        title: "Drive back home",
      },
      {
        day: "sun",
        startTime: "19:00",
        title: "Nice dinner + Momo 😄 + Trip complete 🎉",
      },
    ],
  };
}
